@startuml ClassDiagram_group01


title Mathematical Operation ClassDiagram, Group01.

skinparam ClassAttributeIconSize 0

interface MathInterface{
	+ {abstract} execute(stack : Stack<ComplexNumber>) : void
}

abstract class MathOperation{
	- numOperands: int
	+ MathOperation()	
	+ MathOperation(numOperands : int)
	+ abstract execute(stack : Stack<ComplexNumber>)
	# MinOperandsToOperate(size : int) : boolean
}

class SumOperation{
	+ SumOperation()
	+ execute(stack : Stack<ComplexNumber>) : void
}

class DifferenceOperation{
	+ DifferenceOperation()
	+ execute(stack : Stack<ComplexNumber>) : void
}

class DivisionOperation{
	+ DivisionOperation()
	+ execute(stack : Stack<ComplexNumber>) : void
}

class MultiplicationOperation{
	+ MultiplicationOperation()
	+ execute(stack : Stack<ComplexNumber>) : void
}

class SqrtOperation{
	+ SqrtOperation()
	+ execute(stack : Stack<ComplexNumber>) : void
}

class InverionOperation{
	+ InversionOperation()
	+ execute(stack : Stack<ComplexNumber>) : void
}

MathOperation <.up. MathInterface
MathOperation --> SumOperation
MathOperation --> DifferenceOperation
MathOperation --> DivisionOperation
MathOperation --> MultiplicationOperation
MathOperation --> SqrtOperation
MathOperation --> InverionOperation

@enduml