@startuml ClassDiagram_group01


title Mathematical Operation ClassDiagram, Group01.

skinparam ClassAttributeIconSize 0

interface MathInterface{
	+ {abstract} execute(stack : Stack<ComplexNumber>) : void
}

abstract class MathOperation{
	- numOperands: int
	+ MathOperation()	
	+ MathOperation(numOperands : int)
	+ abstract execute(stack : Stack<ComplexNumber>)
	# MinOperandsToOperate(size : int) : boolean
}

class SumOperation{
	+ SumOperation()
	+ execute(stack : Stack<ComplexNumber>) : void
}

class DifferenceOperation{
	+ DifferenceOperation()
	+ execute(stack : Stack<ComplexNumber>) : void
}

class DivisionOperation{
	+ DivisionOperation()
	+ execute(stack : Stack<ComplexNumber>) : void
}

class MultiplicationOperation{
	+ MultiplicationOperation()
	+ execute(stack : Stack<ComplexNumber>) : void
}

class SqrtOperation{
	+ SqrtOperation()
	+ execute(stack : Stack<ComplexNumber>) : void
}

class InverionOperation{
	+ InversionOperation()
	+ execute(stack : Stack<ComplexNumber>) : void
}

class MathOperation implements MathInterface
class SumOperation extends MathOperation
class DifferenceOperation extends MathOperation
class DivisionOperation extends MathOperation
class MultiplicationOperation extends MathOperation
class SqrtOperation extends MathOperation
class InverionOperation extends MathOperation

@enduml