@startuml ClassDiagram_group01


title Stack Operation ClassDiagram, Group01.

skinparam ClassAttributeIconSize 0

abstract class StackOperation{
	- numOperands: int
	+ MathOperation()	
	+ MathOperation(numOperands : int)
	+ abstract execute(stack : Stack<ComplexNumber>) : void
	# MinOperandsToOperate(size : int) : boolean
}

class ClearOperation{
        + ClearOperation()
        + execute(stack : Stack<ComplexNumber>) : void
}

class DropOperation{
        + DropOperation()
        + execute(stack : Stack<ComplexNumber>) : void
}

class DupOperation{
        + DupOperation()
        + execute(stack : Stack<ComplexNumber>) : void
}

class SwapOperation{
        + SwapOperation()
        + execute(stack : Stack<ComplexNumber>) : void
}

class OverOperation{
        + OverOperation()
        + execute(stack : Stack<ComplexNumber>) : void
}

StackInterface <.down. StackOperation
StackOperation --> ClearOperation
StackOperation --> DropOperation
StackOperation --> DupOperation
StackOperation --> SwapOperation
StackOperation --> OverOperation

@enduml