@startuml ActivityDiagram

start
switch (Input Recognition)
case (It's a MathOperation)
	if (Are there enough operands to operate?) then
		->no;
		#red:stack error;
		kill
	endif
	->yes;
	:Pop operand(s) from Stack;
	if(It's possible to calculate?) then
		->no;
		#red: math error;
		kill
	endif
	->yes;
	:Execute operation;
	:Push result into Stack;

case (It's a StackOperation)
	if (Are there enough operands to operate?) then
		->no;
		#red:stack error;
		kill
	endif
	->yes;
	:Manipulate Stack;

case (It's a VariablesOperation)
	if (It's valid?) then
		->no;
		#red:syntax error;
		kill
	endif
	->yes;
	if (Are there enough operands to operate?) then
		->no;
		#red:stack error;
		kill
	endif
	->yes;
	if (What kind of operation is it?) then
		->Variable to Stack;
		:Update the Stack state;
	else
		->Stack to Variable;
		:Update the Variable state;
	endif
case (It's a ComplexNumber)
	if (It's valid?) then
		->no;
		#red:syntax error;
		kill
	endif
	->yes;
	:Save Complex Number into Stack;
endswitch

-Show last 12 Stack elements
stop

@enduml