@startuml SequenceDiagram

title Complex Number Sequence Diagram, Group01.

participant ScientificCalculator as calc
participant InputDistinguisher as input
participant complexNumbersStack as num_stack


-> calc:calculate()
activate calc

calc -> input : IsComplexNumber()
activate input
input --> calc : ComplexNumber : boolean
deactivate input

calc -> num_stack : saveComplexNumber()
activate num_stack
num_stack -> num_stack : [Update stack]
num_stack --> calc
deactivate num_stack

@enduml