@startuml SequenceDiagram

title General Sequence Diagram, Group01.

participant ScientificCalculator as calc
participant InputDistinguisher as input
participant MathOperation as math
participant StackOperation as stack
participant VariablesOperation as Variables

-> calc:calculate()
activate calc


' math op case starts
alt input is a math operation

calc -> input : IsMathOperation()
activate input
input -> input : checks if input is a mathematical operation
input --> calc : mathOperation : boolean
deactivate input

calc -> calc : calculateMathOperation()

calc -> math : execute()
activate math
math -> math : executes a mathematical operation
math --> calc
deactivate math


' stack op case starts
else input is a stack operation

calc -> input : IsStackOperation()
activate input
input -> input : checks if input is a stack operation
input --> calc : stackOperation : boolean
deactivate input

calc -> calc : calculateStackOperation()

calc -> stack : execute()
activate stack
stack -> stack : executes a stack operation
stack --> calc
deactivate stack


' variables op case starts
else input is a variables operation

calc -> input : IsVariablesOperation()
activate input
input -> input : checks if input is a variables operation
input --> calc : VariablesOperation : boolean
deactivate input

calc -> calc : calculateVariablesOperation()

calc -> Variables : execute()
activate Variables
Variables -> Variables : executes a variables operation 
Variables --> calc
deactivate Variables


' complex number case starts
else input is a complex number 

calc -> input : IsComplexNumber()
activate input
input -> input : checks if input is a complex number
input --> calc : ComplexNumber : boolean
deactivate input

calc -> calc : saveComplexNumber()

end

@enduml