@startuml MathOperation_SequenceDiagram_Group01

title Math Operation Sequence Diagram, Group01.

participant ScientificCalculator as calc
participant InputDistinguisher as input
participant MathOperation as math
participant complexNumbersStack as num_stack

-> calc:calculate()
activate calc

calc -> input : IsMathOperation()
activate input
input -> input : checks if input is a mathematical operation
input --> calc : mathOperation : boolean
deactivate input

calc -> calc : calculateMathOperation()
calc -> math : execute()
activate math
math -> num_stack : execute()
activate num_stack
num_stack -> num_stack : [Update stack]
num_stack --> math
deactivate num_stack
math --> calc
deactivate math

@enduml