@startuml VariablesOperation_SequenceDiagram_Group01

title Variables Operation Sequence Diagram, Group01.

participant ScientificCalculator as calc
participant InputDistinguisher as input
participant VariablesOperation as Variables
participant variablesMap as var_map
participant complexNumbersStack as num_stack

-> calc:calculate()
activate calc

calc -> input : IsVariablesOperation()
activate input
input -> input : checks if input is a variables operation
input --> calc : VariablesOperation : boolean
deactivate input

calc -> calc : calculateVariablesOperation()
calc -> Variables : execute()
activate Variables
alt is a stack to variable operation
Variables -> var_map : execute()
activate var_map
var_map -> var_map : [Update variable]
var_map --> Variables
deactivate var_map
else is a variable to stack operation
Variables -> num_stack : execute()
activate num_stack
num_stack -> num_stack : [Update stack]
num_stack -->Variables
deactivate num_stack
end
Variables --> calc
deactivate Variables

@enduml